gantt
  title AKS Kubernetes Versions
  dateFormat YYYY-MM-DD
  axisFormat %b/%y
  # section K8s v1.24
  #   Upstream release : milestone, 2022-04-22, 1d
  #   Preview          : 2022-05-01, 2022-07-01
  #   Live             : 2022-07-01, 2023-07-31
  #   Support only     : crit, 2023-07-31, 30d
  #   End of Life      : milestone, 2023-08-30, 1d
  section K8s 1.25
    Upstream release : milestone, 2022-08-23, 1d
    Preview          : 2022-10-02, 2022-12-14
    Live             : 2022-12-14, 2023-12-31
    Support only     : crit, 2023-12-31, 30d
    End of Life      : milestone, 2024-01-30, 1d
  section K8s 1.26
    Upstream release : milestone, 2022-12-09, 1d
    Preview          : 2023-02-12, 2023-04-09
    Live             : 2023-04-09, 2024-03-30
    Support only     : crit, 2024-03-30, 30d
    End of Life      : milestone, 2024-04-31, 1d
  section K8s 1.27
    Upstream release : milestone, 2023-04-11, 1d
    Preview          : 2023-06-11, 2023-08-03
    Live             : 2023-08-03, 2024-08-30
    LTS              : crit, 2024-07-31, 1y
    End of Life      : milestone, 2025-07-31, 1d
  # section K8s 1.28
  #   Upstream release : milestone, 2023-08-15, 1d
