# This is a basic workflow to help you get started with Actions

name: Build AKS Support Kubernetes Versions Gantt Chart

# Controls when the workflow will run
on:
  # Run the job on a schedule
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '5 0 * * *' # Run at 00:05 every day

  # # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build the Mermaid Gantt chart
        run: for format in "png" "svg"; do docker run --rm -u `id -u`:`id -g` -v ${PWD}:/data minlag/mermaid-cli:10.3.0 --theme neutral --width 1200 --input kubernetes-versions-gantt.mmd --output kubernetes-versions-gantt-$(date +%Y%m%d).${format}; done
